---

- name: JMX_EXPORTER | Copy exporter config
  template:
    src: "{{ item }}"
    dest: "{{ jmx_exporter_conf_path }}"
    owner: "{{ jmx_exporter_user }}"
    group: "{{ jmx_exporter_group }}"
    mode: 0640
  with_fileglob:
    - "{{ jmx_exporter_config_template_path }}/*"
  notify:
    - restart jmx_exporter
